### ISSUE TITLE
Add follower notification?

### ISSUE THREAD

**Issue by Wikotikabesa** [shughes-uk/twitchy_hue#1]
@shughes-uk 
Could you add a notification when someone follow the channel?
I have not find anything for this in the internet and i can't do it by myself.

I'm streaming on Twitch as a hobby, but I would also let it cost me something. If there is no other way :)

**Comment by shughes-uk** [comment]
I have this implemented in at https://github.com/shughes-uk/physical_twitch_notifications I believe. You'll have to install python to run the script but It should work. Haven't tried it in a while so you'll have to open and issue up over on that project if it doesn't work. Closing this for now.
